name: Update API Documentation

on:
  push:
    branches: [ main ]  # Workflow file should be on main
  repository_dispatch:  # Add manual trigger capability
    types: [update_api_docs]
  workflow_dispatch:    # Allow manual runs from GitHub UI

jobs:
  update-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add explicit permissions
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main    # Explicitly checkout main
      
      - name: Update API documentation
        run: |
          rm -rf public/api
          mkdir -p public/api
          git clone --depth 1 -b api-docs https://github.com/chrischtel/zfitsio.github.io.git temp
          cp -r temp/* public/api/
          rm -rf temp

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/api
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update API documentation" && git push)
