name: Update API Documentation

on:
  push:
    branches: [ api-docs ]

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update API documentation
        run: |
          rm -rf public/api
          mkdir -p public/api
          git clone --depth 1 -b api-docs https://github.com/chrischtel/zfitsio.github.io.git temp
          cp -r temp/* public/api/
          rm -rf temp

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/api
          git commit -m "chore: update API documentation" || echo "No changes to commit"
          git push
